### ISSUE TITLE
Linter is not activating

### ISSUE THREAD

**Issue by Flylowguy** [steelbrain/linter#1133]
I cannot get the linter package to work in atom at all. It doesn't open any error windows but when I go into the developer tools for atom the following error message is there.
```
`Failed to activate package named 'linter' /home/****/.atom/packages/linter/lib/linter-views.js:3
import {Emitter, CompositeDisposable} from 'atom'
^^^^^^
SyntaxError: Unexpected token import
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:451:25)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/****/.atom/packages/linter/lib/linter.coffee:3:15)
  at Object.<anonymous> (/home/****/.atom/packages/linter/lib/linter.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.activate (/home/****/.atom/packages/linter/lib/main.coffee:130:18)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:235:27)
  at /usr/share/atom/resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:453:21)
  at /usr/share/atom/resources/app/src/package-manager.js:434:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:344:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:428:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:411:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)`
```

**Comment by steelbrain** [comment]
Can you please post your Atom version?

**Comment by steelbrain** [comment]
( sorry for closing, wrong button press )

**Comment by Flylowguy** [comment]
I am using 0.174.0

**Comment by Flylowguy** [comment]
I appear to be a special kind of incompetent. All it took was updating to the latest version. I guess I was still on beta and didn't even know it... sorry for wasting your time!

**Comment by steelbrain** [comment]
No problem, glad you figured it out 👍
