### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by frenchbread** [steelbrain/linter#1147]
**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/damir/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/damir/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:47.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:47.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:47 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:42.7.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:26.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:26 core:paste (atom-text-editor.editor.mini.is-focused)
  7x -0:24 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:18.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.7.0 tree-view:move (span.name.icon.icon-file-text)
     -0:10.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 tree-view:open-selected-entry-right (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-javascript-jsx"
    ]
  },
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-json-color, v0.4.2
atom-ternjs, v0.14.1
atom-typescript, v8.9.1
color-picker, v2.1.1
file-icons, v1.7.8
highlight-selected, v0.11.2
linter, v1.11.4
linter-jshint, v2.1.0
minimap, v4.23.2
pretty-json, v1.0.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by frenchbread** [comment]
Duplicate of #1054. Closing this one..
