### ISSUE TITLE
Linter fails at start on atom git: Uncaught TypeError: Invalid Point: (1, NaN)

### ISSUE THREAD

**Issue by paradoxxxzero** [steelbrain/linter#1150]
**Atom Version**: 1.9.0-dev-38ff433
**System**: linux 4.5.3-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught TypeError: Invalid Point: (1, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (1, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1080:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:192:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:74:62)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1571:38)
    at /home/zero/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/zero/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/zero/.atom/packages/linter/lib/linter-views.js:118:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinter (/home/zero/.atom/packages/linter/lib/linter-views.js:116:19)
    at Linter.createEditorLinter (/home/zero/.atom/packages/linter/lib/linter.coffee:104:12)
    at Commands.toggleLinter (/home/zero/.atom/packages/linter/lib/commands.coffee:28:15)
    at atom-workspace.Commands.subscriptions.add.atom.commands.add.linter:toggle (/home/zero/.atom/packages/linter/lib/commands.coffee:9:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:04.6.0 tree-view:reveal-active-file (atom-text-editor.editor.power-mode.is-focused)
     -0:03.8.0 tree-view:move (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:02.7.0 bookmarks:jump-to-next-bookmark (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:01.0 window:toggle-full-screen (atom-text-editor.editor.power-mode.is-focused)
  2x -0:00.4.0 linter:toggle (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "metrics",
      "autocomplete-google-suggest"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pyc",
      "__pycache__"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  },
  "linter": {
    "errorPanelHeight": 32,
    "showErrorPanel": false,
    "statusIconScope": "File"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2 (active)
atom-fuzzy-grep, v0.13.0 (inactive)
atom-jade, v0.3.0 (active)
atom-jinja2, v0.5.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.2.11 (active)
atomic-chrome, v0.3.0 (active)
autocomplete-google-suggest, v1.1.0 (inactive)
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.7.2 (active)
color-picker, v2.1.1 (active)
cursor-indicator, v1.2.7 (active)
dracula-theme, v1.2.5 (inactive)
dracula-ui, v0.3.0 (inactive)
editor-stats, v0.17.0 (active)
git-plus, v5.13.4 (inactive)
git-time-machine, v1.5.2 (inactive)
highlight-bad-chars, v1.0.5 (active)
highlight-selected, v0.11.2 (active)
language-restructuredtext, v0.13.0 (active)
linter, v1.11.4 (active)
linter-eslint, v7.2.2 (active)
linter-flake8, v1.13.0 (active)
linter-jshint, v2.1.0 (active)
linter-less, v2.5.0 (active)
livereload, v0.4.4 (active)
merge-conflicts, v1.4.2 (active)
minimap, v4.23.5 (active)
minimap-cursorline, v0.1.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
pigments, v0.26.2 (active)
python-indent, v0.4.3 (active)
python-isort, v0.0.7 (active)
python-tools, v0.6.7 (active)
shell-it, v0.2.1 (inactive)
split-diff, v0.7.5 (inactive)
sync-settings, v0.7.2 (active)
tornado-templates, v0.2.0 (active)
travis-ci-status, v1.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (inactive)
one-light-ui, v1.3.1 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.10.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.0.6 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.236.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.6 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.93.2 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.5 (active)
language-clojure, v0.20.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.18.0 (active)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.0 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.2 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.51.1 (active)
language-shellscript, v0.22.2 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.27.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.6 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
This is actually a bug in your linter provider, please reopen this in the linter provider

**Comment by paradoxxxzero** [comment]
Alright sorry for the inconvenience
