### ISSUE TITLE
Uncaught TypeError: Invalid Point: (2, NaN)

### ISSUE THREAD

**Issue by andya9** [steelbrain/linter#1171]
When linting a python file using linter-flake8, I get this error:

**Atom Version**: 1.9.0-beta0
**System**: linux 4.5.6.201606051644-2-grsec
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught TypeError: Invalid Point: (2, NaN)

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (2, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1080:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:192:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:74:62)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1574:38)
    at /home/arch/.config/atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/arch/.config/atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/arch/.config/atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/arch/.config/atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/arch/.config/atom/packages/linter/lib/linter-views.js:59:10)
    at /home/arch/.config/atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/arch/.config/atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/arch/.config/atom/packages/linter/lib/message-registry.js:24:16)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "about",
      "archive-view",
      "autocomplete-atom-api",
      "autoflow",
      "autosave",
      "background-tips",
      "deprecation-cop",
      "exception-reporting",
      "image-view",
      "incompatible-packages",
      "keybinding-resolver",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-hyperlink",
      "language-java",
      "language-less",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-property-list",
      "language-ruby-on-rails",
      "language-sql",
      "language-todo",
      "language-toml",
      "markdown-preview",
      "open-on-github",
      "package-generator",
      "styleguide",
      "timecop",
      "welcome",
      "language-make",
      "language-sass",
      "metrics",
      "release-notes",
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-snippets",
      "language-go",
      "spell-check"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ],
    "themes": [
      "one-light-ui",
      "one-o-eight-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 48
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.8.0 (inactive)
autocomplete-python, v1.7.4 (active)
environment, v1.2.0 (active)
file-icons, v1.7.13 (active)
language-markdown, v0.14.0 (active)
linter, v1.11.4 (active)
linter-chktex, v1.3.0 (active)
linter-flake8, v1.13.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v1.2.5 (active)
merge-conflicts, v1.4.4 (active)
one-o-eight-syntax, v0.22.0 (active)
open-in-browser, v0.4.7 (inactive)
tabs-to-spaces, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
This is actually a problem in  your linter provider

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/AtomLinter/linter-flake8/issues/196.
