### ISSUE TITLE
Uncaught TypeError: Invalid Point

### ISSUE THREAD

**Issue by jackwilsdon** [steelbrain/linter#1172]
[Enter steps to reproduce below:]

1. Install [`linter-flake8`](https://atom.io/packages/linter-flake8).
2. Open any Python file.

I'm not sure whether this belongs here or on the `linter-flake8` package, as it seems `linter-flake8` may be causing the error (even though it's nowhere to be seen in the stack trace). If I disable `linter-flake8` the issue goes away.

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught TypeError: Invalid Point: (26, NaN)

```
At /Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (26, NaN)
    at Function.module.exports.Point.assertValid (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1080:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:192:46)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:74:62)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1574:38)
    at /Users/jack/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/jack/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/jack/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/jack/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/jack/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/jack/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/jack/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/jack/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/jack/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:04.1.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "typewriter",
      "autocomplete-clang",
      "markdown-preview-plus",
      "markdown-preview-plus-opener"
    ]
  },
  "linter": {
    "errorPanelHeight": 24
  }
}
```

### Installed Packages

```coffee
# User
atom-easy-jsdoc, v4.6.0 (inactive)
auto-detect-indentation, v1.1.0 (active)
autocomplete-clang, v0.9.3 (inactive)
build, v0.64.0 (active)
busy, v0.5.0 (active)
color-picker, v2.1.1 (active)
docblockr, v0.7.3 (active)
docs-snippets, v0.8.0 (active)
file-icons, v1.7.13 (active)
formatter-tidy, v1.0.1 (active)
jshint, vundefined (active)
language-bnf, v1.1.0 (active)
language-cmake, v0.1.4 (active)
language-diff, v0.4.0 (active)
language-gradle, v0.0.3 (active)
language-groovy, v0.6.0 (active)
language-haml, v0.24.0 (active)
language-html-swig, v2.0.1 (active)
language-ini, v1.16.0 (active)
language-restructuredtext, v0.16.0 (active)
language-rust, v0.4.6 (active)
language-tmux, v0.4.0 (active)
linter, v1.11.4 (active)
linter-eslint, v7.2.2 (active)
linter-flake8, v1.13.0 (active)
linter-gcc, v0.6.14 (active)
linter-htmlhint, v1.1.4 (active)
linter-rust, v0.4.6 (active)
markdown-preview-opener, v0.1.1 (active)
markdown-preview-plus, v2.4.0 (inactive)
markdown-preview-plus-opener, v0.2.0 (inactive)
pigments, v0.29.1 (active)
racer, v0.20.0 (active)
sort-lines, v0.14.0 (inactive)
svg-preview, v0.7.4 (active)
tool-bar, v0.4.0 (active)
xml-formatter, v0.10.0 (inactive)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
This is a bug in linter-flake8, please reopen this in that repo. Thanks
