### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by KurtRMueller** [steelbrain/linter#1177]
[Enter steps to reproduce below:]

1. Click on method signature that where a warning exists that there is a circular argument reference.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.7

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1400:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/mueller.128/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/mueller.128/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:50.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:49.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:49.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:49 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:48.3.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:48.1.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  8x -0:47.8.0 find-and-replace:select-next (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:45.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:45.4.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:45 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:44.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 22x -0:44.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -0:40.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:38.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 10x -0:37.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 14x -0:28.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "useReactEditor": true
  },
  "linter": {
    "subtleLinterErrors": [
      "ruby"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-pair, v2.0.10
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
ex-mode, v0.8.0
html2haml, v0.10.0
language-babel, vundefined
language-cfml, v0.13.0
language-cjsx, v0.3.0
language-docker, v1.1.6
language-elm, v1.5.0
language-ember-htmlbars, v0.3.0
language-emblem, v0.2.0
language-haml, v0.24.0
language-jade, v0.7.1
language-javascript-jsx, v0.3.7
language-puppet, v0.19.1
language-rspec, v0.5.0
linter, v1.11.7
linter-cflint, v0.9.2
linter-clojure, v1.1.2
linter-docker, v0.1.2
linter-ruby, v1.2.2
merge-conflicts, v1.4.4
react, v0.15.0
seti-syntax, v1.0.1
seti-ui, v1.3.1
trailing-spaces, v0.3.2
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by v1.11.8
