### ISSUE TITLE
Cannot find module 'interact.js'

### ISSUE THREAD

**Issue by MCrypa** [steelbrain/linter#1196]
1. Start Atom
2. Read error

Error: Cannot find module 'interact.js'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Jan/.atom/packages/linter-1.11.14/lib/ui/bottom-panel.js:3:18)
    at Module._compile (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Jan/.atom/packages/linter-1.11.14/lib/linter-views.js:3:57)
    at Module._compile (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Jan/.atom/packages/linter-1.11.14/lib/linter.coffee:3:15)
    at Object.<anonymous> (file:///C:/Users/Jan/.atom/packages/linter-1.11.14/lib/linter.coffee:1:1)
    at Module._compile (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///C:/Users/Jan/.atom/packages/linter-1.11.14/lib/main.coffee:130:18)
    at Package.module.exports.Package.activateNow (C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\Jan\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32

**Comment by steelbrain** [comment]
```
cd "C:/Users/Jan/.atom/packages/linter-1.11.14/"
apm install
```
