### ISSUE TITLE
Failed to activate the linter package as dependency of Api Workbench

### ISSUE THREAD

**Issue by araguacaima** [steelbrain/linter#1237]
[Enter steps to reproduce below:]

1. ... Attempting to install Api Workbench (linter is installed as dependency of it)
2. ...

**Atom Version**: 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.16

### Stack Trace

Failed to activate the linter package

```
At Cannot read property 'indexOf' of null

TypeError: Cannot read property 'indexOf' of null
    at AccumulatingRegistry.get (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:222:30)
    at AccumulatingRegistry.TypeRegistry.get (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\typesystem.js:308:33)
    at contributeToAccumulatingRegistry (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:845:50)
    at parse (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:731:18)
    at parsePropertyBean (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:372:19)
    at D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:799:21
    at Array.forEach (native)
    at parse (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:797:34)
    at AccumulatingRegistry.get (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:214:30)
    at D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:325:17
    at Array.forEach (native)
    at Object.parseTypeCollection (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\parse.js:324:25)
    at Object.parseFromAST (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-typesystem\dist\src\index.js:88:15)
    at ASTNodeImpl.types (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:957:38)
    at ASTNodeImpl.types (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:950:38)
    at ASTNodeImpl.parsedType (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:988:130)
    at getBaseType (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:650:19)
    at desc1 (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:774:24)
    at descriminate (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:837:23)
    at D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:622:34
    at Array.forEach (native)
    at D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:621:24
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:261:25)
    at BasicNodeBuilder.process (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:227:32)
    at BasicNodeBuilder.process (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:98:41)
    at ASTNodeImpl.children (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:1407:42)
    at Object.fromUnit (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:1691:9)
    at CompilationUnit.highLevel (D:\Users\MB65788\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\jsyaml\jsyaml2lowLevel.js:64:24)
    at Object.s [as ast] (D:\Users\MB65788\.atom\packages\api-workbench\main.js:3:17808)
```

### Commands

```
     -7:50.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "linter": {
    "errorPanelHeight": 255
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.37 (active)
linter, v1.11.16 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
I have _no_ idea why the error reporter thought this was thrown from `linter`, nothing in that stack trace has anything to do with this package. You should copy the error over to [api-workbench](https://github.com/mulesoft/api-workbench/issues), although from the stack trace it's entirely likely the bug is within the `raml-typesystem` dependency it is bringing in.

**Comment by araguacaima** [comment]
Really thank you @Arcanemagus . I've posted this trace here precisely because it was suggested by Atom when installing the package Workbench. But no problem, I'll post it where it belongs. Again thank you very much for the help ...

**Comment by Arcanemagus** [comment]
By "error reporter" I meant the part of Atom's `notifications` package that decides where to report errors, not you @araguacaima 😉

See https://github.com/atom/notifications/issues/66 for many more examples of this bug.

**Comment by araguacaima** [comment]
Again, thanks for clarification... xD. You rocks!
