### ISSUE TITLE
Error: Prelude.(!!): index too large

### ISSUE THREAD

**Issue by rugk** [steelbrain/linter#1245]
Always get this error after latest update of linter packages:
```
Error: Prelude.(!!): index too large
    at ChildProcess.<anonymous> (/home/USERNAME/.atom/packages/linter-shellcheck/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

When I disable one specific linter (here linter-shellcheck) the same error is shown for another linter. This is why I assume the linter package itself has issues.

Linter 1.11.16
Atom 1.10.2
Linux

**Comment by steelbrain** [comment]
Any idea how to repro this behavior?

**Comment by steelbrain** [comment]
Also, this is relevant https://github.com/AtomLinter/linter-shellcheck/issues/25

**Comment by rugk** [comment]
Not really, now it is working for some reason...

**Comment by steelbrain** [comment]
Thanks for the update. Closing
