### ISSUE TITLE
atom fails to activate linter.

### ISSUE THREAD

**Issue by 315568099** [steelbrain/linter#1250]
atom shows some information :

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.16

### Stack Trace

Failed to activate the linter package

```
At Unexpected token ILLEGAL

SyntaxError: Unexpected token ILLEGAL
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/linter.coffee:7:18)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/linter.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///C:/Users/Administrator/.atom/packages/linter/lib/main.coffee:130:18)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:183:20)
    at C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\buffered-process.js:229:18
    at Socket.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.10.2\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

### Commands

```
     -3:05.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3 (active)
linter, v1.11.16 (active)
open-in-browser, v0.4.7 (inactive)
pigments, v0.35.2 (active)
sort-lines, v0.14.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you try:

* Closing all instances of Atom
* Deleting `C:\Users\Administrator\.atom\packages\linter`
* Running `apm install linter`

If that doesn't work, what version of Windows are you running? Your stack trace shows you are running as the `Administrator` user, which usually indicates something wrong...

**Comment by 315568099** [comment]
I have tried many times , but that doesn't work ,
the version of Window :Windows 7 Ultimate.
there was an electricity black-out   suddenly when I was  installing linter ,so this problem arises.
thank you  for your help.

**Comment by steelbrain** [comment]
`apm uninstall linter` and then `apm install linter` will fix it for you. Let us know how it goes

**Comment by steelbrain** [comment]
No updates for 16 days, closing as outdated. Feel free to continue discussing
