### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by hueper** [steelbrain/linter#1259]
Hello everyone,

thank you for this package :-)

Unfortunately, I'm unable to activate it (Atom: 1.11.2). Any help is appreciated!

![image](https://cloud.githubusercontent.com/assets/6799184/19524502/3f37e476-961e-11e6-9cee-f7b0f2f802d8.png)

Stack trace:
```
TypeError: _uiBottomContainer2.default.create is not a function
    at new LinterViews (/Users/moritzhueper/.atom/packages/linter/lib/linter-views.js:15:44)
    at new Linter (/Users/moritzhueper/.atom/packages/linter/lib/linter.coffee:26:18)
    at Object.module.exports.Linter.activate (/Users/moritzhueper/.atom/packages/linter/lib/main.coffee:132:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:827:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:343:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by steelbrain** [comment]
Hi @hueper!

The error you're hitting seems to be a mysterious one. Can you try to repro this on a fresh atom env?

```
pkill atom
mv ~/.atom ~/.atom-bkp
apm install linter
atom
```

If you still get the error after executing the commands above, then we would further investigate into this. For the reference, I wasn't able to reproduce this behavior on `v1` branch of this repo.

**Comment by hueper** [comment]
thank you @steelbrain, works!
