### ISSUE TITLE
Error: spawn scalac/Usr/local/Cellar/scala/2.12.0/bin ENOENT

### ISSUE THREAD

**Issue by rla3rd** [steelbrain/linter#1280]
Error: spawn scalac/Usr/local/Cellar/scala/2.12.0/bin ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by steelbrain** [comment]
Hi @rla3rd 

The error is self explainatory, you have to install `scala` bin. Regardless though, this belongs to `linter-scalac` not the base `linter` :)
