### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by Bogdan201** [steelbrain/linter#1316]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/atom-community/linter) package 1.11.21

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'interact.js'

Error: Cannot find module 'interact.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-1.11.21/lib/ui/bottom-panel.js:3:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-1.11.21/lib/linter-views.js:3:57)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-1.11.21/lib/linter.coffee:3:15)
    at /packages/linter-1.11.21/lib/linter.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/linter-1.11.21/lib/main.coffee:131:18)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-clock 0.1.3 
autoclose-html 0.24.0 
color-picker 2.2.5 
hey-pane 0.1.0 
linter 1.11.21 
```

**Comment by steelbrain** [comment]
Ah, the good ol' APM bug

The fix is

```
apm uninstall linter
apm install linter
```

**Comment by LR-LL** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.0.0


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'lodash.uniq'

Error: Cannot find module 'lodash.uniq'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter/lib/main.js:11:19)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter/lib/index.js:3:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
emmet 2.4.3 
linter 2.0.0 
monokai 0.21.0 
```

**Comment by steelbrain** [comment]
Hi @LR-LL, it's that APM bug again, same fix should work for you too. If you have cloned the repo manually, make sure to run `npm install` in it

**Comment by LR-LL** [comment]
@steelbrain Thank you very much for your quick reply!  I have run `npm install`. And I have install several others packages successfully. Therefore, I don't why it  failed.

**Comment by LR-LL** [comment]
I'm sorry to delete the issue report just now if I cause some trouble! Because I think I should add a new issue. I comment again. Thank you!

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.0.0


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'lodash.uniq'

Error: Cannot find module 'lodash.uniq'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter/lib/main.js:11:19)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter/lib/index.js:3:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
emmet 2.4.3 
linter 2.0.0 
monokai 0.21.0 
```

**Comment by steelbrain** [comment]
#### Recommended APM way

```
apm uninstall linter
apm install linter
```

#### Git way

```
cd ~/.atom/packages
rm -rf linter
git clone https://github.com/steelbrain/linter
cd linter
npm install
```

If neither of the above options work, then this one surely will
```
mv ~/.atom ~/.atom.bkp
apm install linter
```

**Comment by LR-LL** [comment]
@steelbrain Thank you very much! I installed it successfully just. I tried to run the following command code:
`npm uninstall linter` 
`npm install linter `

**Comment by HotelCalifornia** [comment]
FWIW, I ran into this after updating a bunch of packages (including this one).

I uninstalled/reinstalled using `apm`, and when I reopened Atom, I was greeted with a nice message welcoming me to Linter v2, as well as some prompts to install dependencies.

**Comment by cruzlauroiii** [comment]
this is an error when compiled atom from git, 
i think there is a new way for Buffer is not a constructor

navigator.appVersion
"5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.18.0-dev-1f3bb12a1 Chrome/56.0.2924.87 Electron/1.6.7 Safari/537.36"

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-dev-1f3bb12a1 x64
**Electron**: 1.6.7
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4


### Stack Trace

Failed to activate the linter package

```
At /Users/stellar/.atom/packages/linter/lib/index.js: Buffer is not a constructor

TypeError: /Users/stellar/.atom/packages/linter/lib/index.js: Buffer is not a constructor
    at Converter.toBase64 (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:61:10)
    at Converter.toComment (/Applications/Atom.app/Contents/Resources/app/node_modules/convert-source-map/index.js:65:21)
    at File.generate (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:812:82)
    at File.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:625:17)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:168:19
    at File.wrap (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/babel.js:70:1)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:72:1)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:97:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:229:1)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:1)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:846:1
```

### Commands

```
  3x -4:01.1.0 window:toggle-dev-tools (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
intentions 1.1.2 
lebab 0.10.0 
linter 2.1.4 
linter-eslint 8.1.6 
linter-ui-default 1.2.3 
remove-whitespace 0.2.1 
symbol-gen 1.3.1 
```

**Comment by zbluhm** [comment]
[Enter steps to reproduce below:]

1. copy to packages with git clone
2. cd to linter
3. npm install
4. apm install

**Atom Version**: 1.4.0
**System**: Mac OS X 10.12.5
**Thrown From**: [linter](https://github.com/steelbrain/linter) package, v2.2.0


### Stack Trace

Failed to activate the linter package

```
At Unexpected reserved word

SyntaxError: Unexpected reserved word
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.13.1
linter, v2.2.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@zbluhm Your Atom version is absolutely ancient, please update to a [supported version](https://github.com/steelbrain/linter/blob/v2.2.0/package.json#L18) at minimum, the latest stable version  preferrably.

**Comment by Arcanemagus** [comment]
@cruzlauroiii Your issue must have been a bug in your specific instance of Atom, it never surfaced in v1.18.0 stable.

I'm locking this thread to prevent further unrelated issues from piling in here. Please file a **new** issue if you are directed here or your problem hasn't been addressed.
