### ISSUE TITLE
Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by liwangqian** [steelbrain/linter#1339]
Cannot find module 'minimatch'
Hide Stack Trace
Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\linter\lib\helpers.js:16:18)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/indie-delegate.js:3:52)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/indie-registry.js:3:52)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)

----------------------------------------------------
platform: windows 7 x64
atom: 1.14.4 x64

**Comment by steelbrain** [comment]
Please uninstall and reinstall the package
