### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by hamidabdul1994** [steelbrain/linter#1379]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /home/bridgeit/.atom/packages/linter/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/packages/linter/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/linter-jshint/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/linter-ui-default/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-cform 0.6.0 
atom-cform-yaml 0.4.1 
busy-signal 1.3.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
jshint 1.8.6 
linter 2.1.0 
linter-jshint 3.0.3 
linter-ui-default 1.2.1 
ocaml-indent 0.5.4 
php-cs-fixer 4.1.0 
```

**Comment by steelbrain** [comment]
Hi @hamidabdul1994 

Are you using Nuclide by any chance? See https://github.com/AtomLinter/linter-eslint/issues/594 for debugging tips and if you are using Nuclide or any other remote ftp editing packages then please disable them as packages don't work with newly registered protocols easily. Also if you keep getting that error, please reopen this in the Linter provider. The base linter doesn't handle execution
