### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, uv_chdir

### ISSUE THREAD

**Issue by fedeveloperua** [steelbrain/linter#1403]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.2

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, uv_chdir

```
At /Users/IgorLukashev/.atom/packages/linter/node_modules/graceful-fs/polyfills.js:21

Error: ENOTDIR: not a directory, uv_chdir
    at Error (native)
    at process.chdir (/packages/linter/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/linter-ui-default/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
     -0:59.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-adventurous-syntax.theme-one-dark-ui)
     -0:55.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-adventurous-syntax.theme-one-dark-ui)
     -0:41.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-adventurous-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
adventurous-syntax 0.2.0 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
autocomplete-paths 1.0.5 
busy-signal 1.3.0 
cdn-libs 0.1.2 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
jshint 1.8.6 
linter 2.1.2 
linter-ui-default 1.2.1 
livestyle-atom 0.2.9 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
monokai-seti 0.7.0 
monokai-slate 0.6.0 
pigments 0.39.1 
sync-settings 0.8.1 
```

**Comment by steelbrain** [comment]
It's coming from the `jshint` package, please reopen this issue in their repo
