### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by nazarioa** [steelbrain/linter#1408]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_cwd

```
At /Users/nazario/.atom/packages/linter/node_modules/graceful-fs/polyfills.js:11

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/packages/linter/node_modules/graceful-fs/polyfills.js:11:19)
    at process.cwd (/packages/linter-tslint/node_modules/graceful-fs/polyfills.js:11:19)
    at process.cwd (/packages/linter-ui-default/node_modules/graceful-fs/polyfills.js:11:19)
    at process.cwd (/packages/atom-typescript/node_modules/graceful-fs/polyfills.js:11:19)
    at resolve (path.js:1144:25)
    at normalisePath (/packages/file-icons/node_modules/alhadis.utils/index.js:1224:10)
    at list.items.map.item (/packages/file-icons/lib/consumers/fuzzy-finder.js:157:22)
    at Array.map (native)
    at timeouts.set.setTimeout (/packages/file-icons/lib/consumers/fuzzy-finder.js:155:15)
```

### Commands

```
 20x -1:03.3.0 core:undo (input.hidden-input)
     -0:56.5.0 core:save (input.hidden-input)
     -0:55 core:undo (input.hidden-input)
     -0:52.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:49.3.0 core:confirm (input.hidden-input)
     -0:43.3.0 core:save (input.hidden-input)
     -0:42.4.0 core:close (input.hidden-input)
     -0:25.7.0 refactor:done (input.hidden-input)
     -0:25.7.0 editor:newline (input.hidden-input)
     -0:22.8.0 core:move-up (input.hidden-input)
     -0:22.4.0 core:move-right (input.hidden-input)
     -0:20.1.0 core:move-down (input.hidden-input)
  3x -0:15.1.0 core:backspace (input.hidden-input)
     -0:07.3.0 core:move-left (input.hidden-input)
     -0:07.0 refactor:done (input.hidden-input)
     -0:07.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
angular2-snippets-atom 0.7.0 
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
autoclose-html 0.23.0 
busy-signal 1.3.0 
cursor-history 0.9.1 
emmet 2.4.3 
file-icons 2.1.1 
git-plus 7.3.3 
git-time-machine 1.5.9 
intentions 1.1.2 
js-refactor 0.7.5 
jshint 1.8.6 
linter 2.1.2 
linter-tslint 0.15.0 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
package-sync 1.1.0 
pigments 0.39.1 
refactor 0.11.3 
script 3.14.1 
split-diff 1.3.0 
```

**Comment by steelbrain** [comment]
Hi @nazarioa 

This is coming from `atom-typescript`, can you please reopen this issue in their repo?
