### ISSUE TITLE
Pipe error on lintserver

### ISSUE THREAD

**Issue by AntonioSaragga** [steelbrain/linter#1413]
Hello
I am getting the following error message ENOENT on Atom 1.12.5

Error: connect ENOENT \.\pipe\lintserver11208ZqSxlPblS5ngsock
Error: connect ENOENT \\.\pipe\lintserver11208ZqSxlPblS5ngsock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

Any help would be much appreciated

**Comment by steelbrain** [comment]
Hi @AntonioSaragga 

This repo is just the base linter, can you please reopen this in linter-julia? Thanks!
