### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-debounce'

### ISSUE THREAD

**Issue by 916608676** [steelbrain/linter#1441]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta3 ia32
**Electron**: 1.3.14
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4

### Stack Trace

Uncaught Error: Cannot find module 'sb-debounce'

```
At module.js:457

Error: Cannot find module 'sb-debounce'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:66:1)
    at /packages/linter-master/lib/editor-linter.js:3:64)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:66:1)
    at /packages/linter-master/lib/editor-registry.js:3:52)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/native-compile-cache.js:66:1)
    at Linter.registryEditorsInit (/packages/linter-master/lib/main.js:143:25)
    at Linter.registryEditorsIdleInit (/packages/linter-master/lib/main.js:128:14)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 0.4.1 
activate-power-mode 1.4.0 
linter-gcc 0.7.1 
linter 2.1.4 
```

**Comment by steelbrain** [comment]
Either it's an APM bug or you cloned the repo without running `npm install`.

Solution is to uninstall and reinstall
