### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by phpdever** [steelbrain/linter#1445]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At module.js:457

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at linterDepsInstall (/packages/linter/lib/index.js:80:9)
```

### Commands

```
```

### Non-Core Packages

```
simplified-chinese-menu 3.5.0 
file-type-icons 1.3.3 
linter 2.1.4 
```

**Comment by Arcanemagus** [comment]
Please re-install the package, APM has a rare bug that you have unfortunately hit where it fails to install all dependencies.

**Comment by phpdever** [comment]
thanks
