### ISSUE TITLE
Uncaught Error: Invalid Parameters to setMessages()

### ISSUE THREAD

**Issue by bleilei** [steelbrain/linter#1458]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4

### Stack Trace

Uncaught Error: Invalid Parameters to setMessages()

```
At C:\Users\user\.atom\packages\linter\lib\indie-delegate.js:61

Error: Invalid Parameters to setMessages()
    at IndieDelegate.setMessages (/packages/linter/lib/indie-delegate.js:61:13)
    at /packages/vue-migration-help/lib/vue-migration-help.js:87:16
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at TextEditor.module.exports.TextEditor.destroyed (/app.asar/src/text-editor.js:579:20)
    at TextEditor.module.exports.Model.destroy (/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:660:18)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
animate-css 0.1.4 
atom-beautify 0.29.24 
atom-compile-less 0.12.0 
atom-js-console 1.2.2 
atom-js-standard 1.0.2 
atom-json-color 0.6.0 
atom-json-editor 0.4.1 
atom-less 0.1.10 
atom-nodejs-snippets 1.5.0 
auto-id-class 0.2.6 
autoclose-html 0.23.0 
autocomplete-css-with-stylus-support 1.0.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.4.0 
build 0.67.0 
build-stylus 0.8.1 
busy 0.7.0 
busy-signal 1.4.1 
class-complete 6.2.2 
colorful-json 1.1.0 
css-from-html 0.1.5 
css-spy 0.6.0 
css-to-stylus 1.1.3 
es6-javascript 1.0.0 
html-head-snippets 0.2.0 
html-id-class-snippets 1.4.1 
html-nested-comments 3.3.1 
html-outliner 0.1.1 
html-template-generator 0.3.0 
html-to-css 0.2.2 
html-to-elm 0.2.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
jsonpp 0.1.1 
language-javascript-jsx 0.3.7 
language-js-inline-hbs 0.8.0 
language-js-specs 0.1.0 
language-stylus 0.2.0 
language-vue 0.21.2 
language-vue-component 0.5.0 
less-autocompile 1.0.0 
linter 2.1.4 
linter-json-lint 0.1.1 
linter-less 2.6.0 
linter-lesshint 3.0.2 
linter-ui-default 1.2.4 
node-debugger 1.10.1 
node-requirer 0.1.12 
node-resolver 1.0.1 
node-snippets 0.0.7 
pretty-json 1.6.3 
quick-vue 0.1.0 
source-preview 0.5.0 
source-preview-stylus 0.1.7 
Stylus 3.1.0 
stylus-autocompile 0.6.1 
svn 0.0.13 
vue-autocomplete 0.1.1 
vue-element-ui-snippets 0.7.0 
vue-format 0.4.0 
vue-hyperclick 0.2.0 
vue-migration-help 0.2.2 
vue-snippets 0.6.0 
vue-syntax 2.0.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs-snippets 0.1.0 
vuejs2-snippets 0.8.0 
```

**Comment by bleilei** [comment]
newstudy

**Comment by steelbrain** [comment]
Hi @bleilei 

It looks like one of the linter providers you've installed is using the Linter Indie API incorrectly. Can you focus the file where it breaks and invoke `Linter: Debug` from command palette? The debug information will be very useful

**Comment by steelbrain** [comment]
Closing as no reply posted in more than a year.
