### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-config-file'

### ISSUE THREAD

**Issue by evandojunior** [steelbrain/linter#1484]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.4

### Stack Trace

Uncaught Error: Cannot find module 'sb-config-file'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/linter/lib/linter-registry.js:17:21)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at Linter.registryLintersInit (/packages/linter/lib/main.js:132:7)
    at /packages/linter/lib/main.js:121:57
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at /packages/linter/lib/editor-linter.js:26:20
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -5:48.3.0 core:confirm (input.hidden-input)
     -4:37.8.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -4:34.7.0 core:confirm (input.hidden-input)
     -3:22 core:paste (input.hidden-input)
     -2:55.2.0 core:select-all (input.hidden-input)
     -2:54.1.0 core:confirm (input.hidden-input)
     -2:30.5.0 core:select-all (input.hidden-input)
     -2:28.3.0 core:confirm (input.hidden-input)
     -0:39.2.0 command-palette:toggle (input.hidden-input)
     -0:37.9.0 core:confirm (input.hidden-input)
     -0:37.9.0 linter-eslint:fix-file (input.hidden-input)
     -0:30 find-and-replace:show (input.hidden-input)
  2x -0:28.3.0 core:confirm (input.hidden-input)
     -0:27 editor:consolidate-selections (input.hidden-input)
     -0:27 core:cancel (input.hidden-input)
  2x -0:24.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.8 
atom-nodejs-snippets 1.5.0 
busy-signal 1.4.3 
es6-javascript 1.0.0 
es6-snippets 0.3.0 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
laravel 0.7.1 
laravel-5-snippets 0.8.0 
laravel-eloquent-snippets 2.0.0 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-autohide 0.10.1 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-selection 4.4.0 
nodejs-snippets 2.0.2 
php-cs-fixer 4.1.0 
platformio-ide-terminal 2.5.1 
```

**Comment by steelbrain** [comment]
Restart your Atom Editor.

This is a post-update error
