### ISSUE TITLE
error if used rule "indent" with option "flatTernaryExpressions" 

### ISSUE THREAD

**Issue by boggddan** [steelbrain/linter#1497]
I used `Windows 10 x64`, `Atom 1.18.0 x64`, `Liner: 2.2.0`

Sample:
```js
/*eslint indent: ["error", 4, { "flatTernaryExpressions": true }]*/

var a = foo
  ? bar : baz
    ? qux : boop;
```

Console:
```
<embedded>:70798 D:\ProjectRuby\table_test\src\js\test.js line 3:
	Configuration for rule "indent" is invalid:
	Value "data["1"].flatTernaryExpressions" has additional properties.
 Error: D:\ProjectRuby\table_test\src\js\test.js line 3:
	Configuration for rule "indent" is invalid:
	Value "data["1"].flatTernaryExpressions" has additional properties.

    at Object.validateRuleOptions (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-validator.js:109:15)
    at Object.keys.forEach.name (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:368:39)
    at Array.forEach (native)
    at ast.comments.forEach.comment (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:365:44)
    at Array.forEach (native)
    at modifyConfigsFromComments (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:331:18)
    at EventEmitter.module.exports.api.verify (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\eslint.js:834:26)
    at processText (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:264:31)
    at CLIEngine.executeOnText (C:\Users\User\.atom\packages\linter-eslint\node_modules\eslint\lib\cli-engine.js:754:26)
    at lintJob (file:///C:/Users/User/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (file:///C:/Users/User/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by steelbrain** [comment]
This is actually an issue in your ESLint configuration and not the base linter package

**Comment by boggddan** [comment]
An error message is displayed only in Atom
not errors when used eslint in the console 

```bash
eslint src/js/test.js

D:\ProjectRuby\table_test\src\js\test.js
  5:5  error  'a' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by steelbrain** [comment]
Can you reopen this on linter-eslint then?

**Comment by boggddan** [comment]
> Can you reopen this on linter-eslint then?

This error always appears in the Atom, when used settings { "flatTernaryExpressions": true }. 
i could send screenshots with settings linter and eslint plugins if you need you.

**Comment by steelbrain** [comment]
This package is the base Atom Linter and does not understand ESLint, to make it understand and integrate with ESLint there's a package called [`linter-eslint`](https://atom.io/packages/linter-eslint). I was suggesting you should open an issue there because it's out of scope of this package and it works in CLI ESLint so might be an issue in that package

**Comment by boggddan** [comment]
Thank's
