### ISSUE TITLE
ecmaFeatures error in dev console

### ISSUE THREAD

**Issue by evanzhoe** [steelbrain/linter#1507]
Hi, how do I solve this? I am not able to use ESLint in Atom

I'm using version 3.2.0

Error running ESLint Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

![image](https://user-images.githubusercontent.com/26191882/27820350-302abffe-60d9-11e7-8265-719fdbd18ce7.png)

Log:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/.eslintrc Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/.eslintrc
    at validateConfigSchema (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-validator.js:187:15)
    at Object.validate (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-validator.js:200:5)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight.e (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight.e (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:182:43)
    at Config.getConfigVector (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:330:29)
    at processText (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/cli-engine.js:667:26)
    at lintJob (/Users/Ah_Hoehoe_xD/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (/Users/Ah_Hoehoe_xD/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Linter] Error running ESLint Error: [object Object]:(…)
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/.eslintrc Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/.eslintrc
    at validateConfigSchema (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-validator.js:187:15)
    at Object.validate (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-validator.js:200:5)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight.e (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight.e (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:182:43)
    at Config.getConfigVector (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/config.js:330:29)
    at processText (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/Users/Ah_Hoehoe_xD/GitHub/ReactNative-Course/TutorialWorkspace1/albums/node_modules/eslint/lib/cli-engine.js:667:26)
    at lintJob (/Users/Ah_Hoehoe_xD/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (/Users/Ah_Hoehoe_xD/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Linter] Error running ESLint Error: [object Object]:(…)

**Comment by steelbrain** [comment]
Bug in ESLint configuration. ESLint config is too old for the ESLint you're using it with. Although it's off-topic, you could try npm-installing in your package because linter-eslint might be falling back to it's bundled latest version while your project depends on an older one.
