### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-callsite'

### ISSUE THREAD

**Issue by sarderiftekhar** [steelbrain/linter#1509]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught Error: Cannot find module 'sb-callsite'

```
At module.js:457

Error: Cannot find module 'sb-callsite'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-path/lib/index.js:9:18)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:51:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at installLinterJSHintDeps (/packages/linter-jshint/lib/main.js:39:9)
```

### Commands

```
     -0:15.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.3 
atom-brackets-glow 0.4.0 
atom-live-server 2.1.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.8 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-pigments 0.2.2 
pigments 0.39.1 
todo 0.6.0 
```

**Comment by steelbrain** [comment]
APM Installation issue. You should uninstall and reinstall the linter package to fix.

```
apm uninstall linter
apm install linter
```
