### ISSUE TITLE
At Cannot find module 'sb-config-file'

### ISSUE THREAD

**Issue by jmurowaniecki** [steelbrain/linter#1512]
1. Download Atom
2. Installing some packages
3. Opening project
4. :boom:

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/toggle-view.js:13:21)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/main.js:8:39)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/index.js:3:34)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
```

### Commands

```
```

### Non-Core Packages

```
atom-minify 0.8.0 
es6-javascript 1.0.0 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
linter 2.1.1 
minimap 4.28.3 
minimap-autohide 0.10.1 
minimap-git-diff 4.3.1 
minimap-linter 2.0.2 
pretty-json 1.6.3 
```

P.S.: even after proceed to `apm uninstall linter && apm install linter`, tons of Atom reboots and dependencies installed :sob: 

![captura de tela de 2017-07-19 21-51-17](https://user-images.githubusercontent.com/1261167/28396078-66c17c36-6ccf-11e7-9943-f5010c52565b.png)
![captura de tela de 2017-07-19 21-51-24](https://user-images.githubusercontent.com/1261167/28396084-6fd4fae6-6ccf-11e7-9b04-05107b2e5683.png)
![captura de tela de 2017-07-19 22-05-02](https://user-images.githubusercontent.com/1261167/28396086-6fd76cf4-6ccf-11e7-92e1-7f9e8e171e7a.png)
![captura de tela de 2017-07-19 22-05-10](https://user-images.githubusercontent.com/1261167/28396087-6fd8c3a6-6ccf-11e7-85c0-91a903b57b11.png)

_P.S.²: Possibly related to https://github.com/steelbrain/linter/issues/1316_

**Comment by steelbrain** [comment]
Hi @jmurowaniecki

Could you try restarting Atom and see if that fixes it?

**Comment by jmurowaniecki** [comment]
Yep, countless times. :cry: 

Previously I had an outdated version of Atom - so I downloaded a recent one, installed it and updated everything I could.. But the bug still follows.

**Comment by steelbrain** [comment]
Sometimes APM messes up the installing dependencies, so uninstall/resinstall should fix this

**Comment by jmurowaniecki** [comment]
Yes, thinking of it I've tried to solve this question updating not just the packages but the Atom itself.

I noticed a strange behavior now in regardts to start `atom .` in the given project folder or when I just start it by the launcher - it seems to appear more errors when runs from command line/project folder.

I don't know if what I'm sayin makes some sense :roll_eyes:

**Comment by jmurowaniecki** [comment]
Anyway it seems to be much more an environmental issue than something related to linter package.

I think it's better close this issue until we can do more testing about :thinking:
