### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-promisify'

### ISSUE THREAD

**Issue by q837477816** [steelbrain/linter#1521]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught Error: Cannot find module 'sb-promisify'

```
At C:\Users\倥倥倥倥倥\AppData\Local\atom\app-1.18.0\resources\app\static\<embedded>:1

Error: Cannot find module 'sb-promisify'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (C:/Users/%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/sb-fs/lib/index.js:7:20)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Users/%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:135:13)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Users/%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:55:16)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Users/%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5%E5%80%A5/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at installLinterUIDefaultDeps (/packages/linter-ui-default/lib/index.js:22:9)
```

### Commands

```
     -4:32 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:42 core:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
jquery-snippets 11.0.0 
language-vue 0.23.1 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
minimap 4.29.3 
monokai 0.24.0 
simplified-chinese-menu 5.3.4 
```

**Comment by Arcanemagus** [comment]
Can you please try re-installing the package? Occasionally Atom fails to properly install all dependencies.

**Comment by steelbrain** [comment]
Closing because is APM bug (uninstall/reinstall fixes) and no more info provided in more than a week
