### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-fs'

### ISSUE THREAD

**Issue by JulioPerezAG** [steelbrain/linter#1524]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Windows 10 Pro version 1703 compilation 15063.540
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught Error: Cannot find module 'sb-fs'

```
At C:\Users\JulioAdan\AppData\Local\atom\app-1.19.0\resources\app\static\<embedded>:1

Error: Cannot find module 'sb-fs'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:135:13)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:180:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:55:16)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:84:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at installLinterJSHintDeps (/packages/linter-jshint/lib/main.js:39:9)
```

### Commands

```
     -7:01.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  3x -5:28.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.4 
minimap 4.29.6 
pigments 0.40.2 
```

**Comment by steelbrain** [comment]
Ahh the good ol' APM bug.

Fix:

Rename `$HOME/.atom` to `$HOME/.atom-bkp` and reinstall everything

**Comment by steelbrain** [comment]
Closing because is APM bug and no more info provided in a week
