### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.uniq'

### ISSUE THREAD

**Issue by Aleksrepetskiy** [steelbrain/linter#1537]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash.uniq'

```
At C:\Users\Пользователь\AppData\Local\atom\app-1.19.4\resources\app\static\<embedded>:1

Error: Cannot find module 'lodash.uniq'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.4/resources/app/src/module-cache.js:354:58)
    at Module.require (C:/Users/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/helpers.js:3:34)
    at /packages/linter/lib/helpers.js:148:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/editor-linter.js:4:35)
    at /packages/linter/lib/editor-linter.js:8:34)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/lib/editor-registry.js:3:52)
    at /packages/linter/lib/editor-registry.js:59:32)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.4/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AppData/Local/atom/app-1.19.4/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at Linter.registryEditorsInit (/packages/linter/lib/main.js:118:25)
    at Linter.registryEditorsIdleInit (/packages/linter/lib/main.js:103:14)
```

### Commands

```
     -0:55.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-new-file 0.5.0 
atom-beautify 0.30.5 
atom-jade 0.3.0 
atom-live-server 2.1.2 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-paths 2.8.1 
busy-signal 1.4.3 
color-picker 2.2.5 
copy-path 0.4.2 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.11 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-jade 0.7.2 
language-pug 0.0.21 
language-pug-jade 0.2.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.8 
livereload 0.4.4 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pigments 0.40.2 
project-plus 1.0.0 
Remote-FTP 1.1.3 
source-preview-pug 0.2.0 
sync-settings 0.8.3 
terminal-plus 0.14.5 
```

**Comment by steelbrain** [comment]
Can you try uninstalling and then reinstalling the linter package?

**Comment by Aleksrepetskiy** [comment]
Yes, I did, but the error did not disappear.

**Comment by aminya** [comment]
Please install the latest version.
