### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by megamaiku** [steelbrain/linter#1546]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'pageX' of undefined

```
At /Users/mikey/.atom/packages/linter/node_modules/interact.js/interact.js:649

TypeError: Cannot read property 'pageX' of undefined
    at getXY (/packages/linter/node_modules/interact.js/interact.js:649:23)
    at getPageXY (/packages/linter/node_modules/interact.js/interact.js:666:13)
    at setEventXY (/packages/linter/node_modules/interact.js/interact.js:610:9)
    at Interaction.setEventXY (/packages/linter/node_modules/interact.js/interact.js:1319:55)
    at Interaction.pointerMove (/packages/linter/node_modules/interact.js/interact.js:1782:22)
    at /packages/linter/node_modules/interact.js/interact.js:3348:36)
```

### Commands

```
     -9:35.8.0 auto-update-packages:update-now (a.)
  2x -6:44.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-cobalt2-syntax.theme-one-dark-ui)
     -1:23.4.0 core:confirm (input.hidden-input)
     -0:31.7.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.16 
atom-html-preview 0.1.22 
atom-live-server 1.2.5 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
cobalt2-syntax 0.4.0 
highlight-selected 0.11.2 
language-babel 2.74.2 
less-than-slash 0.16.0 
linter 2.2.0 
linter-bootlint 1.0.2 
linter-csslint 1.3.3 
linter-eslint 8.0.0 
linter-tidy 2.3.0 
minimap 4.25.7 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.4.0 
minimap-split-diff 0.3.2 
open-recent 5.0.0 
pigments 0.37.0 
react 0.16.1 
split-diff 1.1.0 
```

**Comment by Arcanemagus** [comment]
`interact.js` isn't even a dependency of this package... at any nesting level, so this makes _no_ sense. Any idea how this triggered for you?

**Comment by megamaiku** [comment]
I was 100% sure I had restarted Atom, but I guess I hadn't. Once I did, the issue went away. I'll close this issue now. Thanks.
