### ISSUE TITLE
[Linter] Error running Flake8

### ISSUE THREAD

**Issue by watashi-Amine** [steelbrain/linter#1563]
```
[Linter] Error running Flake8 Error: c:\users\xXx\appdata\local\programs\python\python37\lib\site-packages\pep8.py:102: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (C:\Users\xXx\.atom\packages\linter-flake8\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Hi,
i use atom the last  version 1.23.1.

**it's because i installed the last version of python 3.7 ?**

**Comment by Arcanemagus** [comment]
It definitely looks like `pep8` (used internally in `flake8`) throws a warning with that version of Python.

For future reference this should have been filed on `linter-flake8`, `linter` is just the "manager" package.
