### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by yangfei19881024** [steelbrain/linter#1564]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'pageX' of undefined

```
At /Users/andy/.atom/packages/linter/node_modules/interact.js/interact.js:649

TypeError: Cannot read property 'pageX' of undefined
    at getXY (/packages/linter/node_modules/interact.js/interact.js:649:23)
    at getPageXY (/packages/linter/node_modules/interact.js/interact.js:666:13)
    at setEventXY (/packages/linter/node_modules/interact.js/interact.js:610:9)
    at Interaction.setEventXY (/packages/linter/node_modules/interact.js/interact.js:1319:55)
    at Interaction.pointerMove (/packages/linter/node_modules/interact.js/interact.js:1782:22)
    at /packages/linter/node_modules/interact.js/interact.js:3348:36)
```

### Commands

```
     -2:46.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.panel-shadows.panel-contrast.use-animations.compact-tree-view.theme-solarized-light-syntax.theme-atom-material-ui.has-custom-icons)
     -2:37.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:40.5.0 core:paste (input.hidden-input)
     -0:07.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.13 
atom-handlebars 1.3.0 
atom-html-preview 0.1.22 
atom-material-ui 1.3.6 
atom-transpose 0.3.4 
atom-wx 0.1.1 
atom-wxml 0.4.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 1.0.2 
autocomplete-ruby 0.1.0 
dash 1.6.2 
editorconfig 2.0.5 
erb-helper 1.0.1 
es6-snippets 0.3.0 
file-icons 1.7.19 
git-plus 5.17.1 
git-time-machine 1.5.3 
html2jade-plus 1.0.0 
language-babel 2.42.0 
language-ejs 0.2.0 
language-haml 0.24.0 
language-jade 0.7.2 
linter 2.2.0 
linter-cpplint 1.0.1 
linter-erb 1.0.2 
linter-eslint 7.3.2 
linter-haml 1.2.1 
linter-htmlhint 1.3.0 
linter-javac 1.9.4 
linter-js-yaml 1.2.5 
linter-jsonlint 1.3.0 
linter-rubocop 0.4.7 
linter-xmllint 1.3.6 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.1 
merge-conflicts 1.4.4 
monokai 0.18.0 
pigments 0.35.1 
rails-snippets 2.8.0 
regex-railroad-diagram 0.16.0 
ruby-syntax-replacer 0.5.1 
script 3.10.1 
sort-lines 0.14.0 
tabs-to-spaces 1.0.2 
terminal-plus 0.14.5 
travis-ci-status 1.3.0 
vue2-autocomplete 0.1.0-alpha.4 
Zen 0.16.4 
```

**Comment by Arcanemagus** [comment]
Do you remember what you were doing when this triggered? The stack trace is only f5rom a dependency here, which might have been used from some other package.

**Comment by steelbrain** [comment]
Closing as no reply provided in a year.
