### ISSUE TITLE
[Linter] Error running PHP

### ISSUE THREAD

**Issue by YunoSiwa** [steelbrain/linter#1566]
C:\Users\usuario\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running PHP Error: "php" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
    at ChildProcess.<anonymous> (C:\Users\usuario\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by steelbrain** [comment]
Hi @YunoSiwa 

The error seems to be coming from `linter-php` and the error seems to indicate that you don't have `php` in your `$PATH`. Please try installing PHP or if you have it installed already, adding it to your $PATH or reflecting it's path in `linter-php`'s `executablePath` config

See https://github.com/AtomLinter/linter-php#setup for more info
