### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by mpskeeter** [steelbrain/linter#1567]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Parrot 3.11
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At /opt/atom/resources/app/src/native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/sb-exec/lib/helpers.js:61:15)
    at /packages/linter/node_modules/sb-exec/lib/helpers.js:167:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/sb-exec/lib/index.js:111:16)
    at /packages/linter/node_modules/sb-exec/lib/index.js:148:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:147:15)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:180:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:55:16)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:84:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at installLinterUIDefaultDeps (/packages/linter-ui-default/lib/index.js:22:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-react-autocomplete 0.1.10 
atom-react-preview 2.0.0 
atom-react-snippets 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
css-grid-snippets 1.1.0 
emmet 2.4.3 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.10.0 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
html-shorcuts-react 2.1.0 
intentions 1.1.5 
language-babel 2.82.0 
language-graphql 0.9.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
local-history 4.3.1 
pretty-json 1.6.4 
pure-syntax 0.3.0 
react 0.17.0 
react-es6-snippets 0.3.0 
react-native-components 0.1.1 
react-snippets 1.0.1 
tree-view-git-status 1.4.0 
```

**Comment by Arcanemagus** [comment]
Is this a custom build of Atom?

**Comment by aminya** [comment]
Closing due to lack of a response
