### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-exec'

### ISSUE THREAD

**Issue by Zangoran** [steelbrain/linter#1599]
**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.2.0

### Stack Trace

Uncaught Error: Cannot find module 'sb-exec'

```
At module.js:545

Error: Cannot find module 'sb-exec'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:147:15)
    at /packages/linter/node_modules/atom-package-deps/lib/helpers.js:180:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:55:16)
    at /packages/linter/node_modules/atom-package-deps/lib/index.js:84:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at installMinimapLinterDeps (/packages/minimap-linter/lib/minimap-linter.js:17:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-increment 0.3.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
color-picker 2.3.0 
file-icons 2.1.25 
git-plus 8.1.0 
Hydrogen 2.6.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.1 
linter-eslint 8.4.1 
linter-htmlhint 1.5.1 
linter-javac 1.9.4 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-linter 2.2.0 
minimap-pigments 0.2.2 
pigments 0.40.2 
```

**Comment by steelbrain** [comment]
Looks like an APM package installation issue. This should be a one-time thing, uninstall/reinstall of linter should fix this.

Closing but lmk if that doesn't work.
