### ISSUE TITLE
Uncaught TypeError: (0 , _helpers.subscriptiveObserve) is not a function

### ISSUE THREAD

**Issue by alex-r-bigelow** [steelbrain/linter#1612]
Steps to reproduce:

1. Update the package in Atom

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.3.0

### Stack Trace

Uncaught TypeError: (0 , _helpers.subscriptiveObserve) is not a function

```
At C:\Users\Home\.atom\packages\linter\lib\editor-linter.js:39

TypeError: (0 , _helpers.subscriptiveObserve) is not a function
    at /packages/linter/lib/editor-linter.js:39:7)
    at EditorRegistry.createFromTextEditor (/packages/linter/lib/editor-registry.js:40:20)
    at /packages/linter/lib/editor-registry.js:28:14
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:428051)
    at EditorRegistry.activate (/packages/linter/lib/editor-registry.js:27:22)
    at Linter.registryEditorsInit (/packages/linter/lib/main.js:124:26)
    at Linter.registryEditorsIdleInit (/packages/linter/lib/main.js:94:14)
```

### Non-Core Packages

```
busy-signal 2.0.0 
colorbrewer-8-dark2-syntax 0.3.0 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.3.0 
linter-docker 0.3.2 
linter-eslint 8.5.1 
linter-ui-default 1.7.1 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? I'm not entirely sure how you hit this error and am unable to reproduce it myself.

**Comment by alex-r-bigelow** [comment]
It seems to have gone away after restarting Atom (it only happened after I manually updated from the previous version).
