### ISSUE TITLE
Uncaught TypeError: _linterRegistry2.default is not a constructor

### ISSUE THREAD

**Issue by mikusher** [steelbrain/linter#1617]
[Enter steps to reproduce:]

1. update plugins
2. open the atom

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.3.0

### Stack Trace

Uncaught TypeError: _linterRegistry2.default is not a constructor

```
At C:\Users\laneves\.atom\packages\linter\lib\main.js:130

TypeError: _linterRegistry2.default is not a constructor
    at Linter.registryLintersInit (/packages/linter/lib/main.js:130:28)
    at /packages/linter/lib/main.js:113:14
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at EditorLinter.lint (/packages/linter/lib/editor-linter.js:52:18)
    at EditorRegistry.createFromTextEditor (/packages/linter/lib/editor-registry.js:47:20)
    at /packages/linter/lib/editor-registry.js:28:14
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:428051)
    at EditorRegistry.activate (/packages/linter/lib/editor-registry.js:27:22)
    at Linter.registryEditorsInit (/packages/linter/lib/main.js:124:26)
    at Linter.registryEditorsIdleInit (/packages/linter/lib/main.js:94:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 13.1.0 
busy-signal 2.0.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.3.0 
linter-ui-default 1.7.1 
```

**Comment by aminya** [comment]
Please install the latest version.
