### ISSUE TITLE
Uncaught TypeError: _editorRegistry2.default is not a constructor

### ISSUE THREAD

**Issue by MartinFrystak** [steelbrain/linter#1655]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.3.1

### Stack Trace

Uncaught TypeError: _editorRegistry2.default is not a constructor

```
At /Users/martinfrystak/.atom/packages/linter/lib/main.js:109

TypeError: _editorRegistry2.default is not a constructor
    at Linter.registryEditorsInit (/packages/linter/lib/main.js:109:28)
    at Linter.registryEditorsIdleInit (/packages/linter/lib/main.js:94:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
Delete-Whitelines 0.6.4 
editorconfig 2.5.0 
emmet 2.4.3 
highlight-bad-chars 2.0.0 
highlight-selected 0.16.0 
intentions 1.1.5 
language-latte 0.4.0 
language-smarty 1.8.0 
linter 2.3.1 
linter-sass-lint 1.9.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
pigments 0.40.2 
postcss-sorting 2.10.0 
section-comment-snippets 2.4.1 
Sublime-Style-Column-Selection 1.7.5 
uikit-atom 0.3.2 
```

**Comment by steelbrain** [comment]
If I had to take a blind guess, this is due to stale Babel compile cache of Atom, are you able to reproduce this after a restart?
