### ISSUE TITLE
linter 2.3.1

### ISSUE THREAD

**Issue by pawanseth** [steelbrain/linter#1699]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.3.1

### Stack Trace

Failed to activate the linter package

```
At Invalid or unexpected token

C:\Users\Pawan\.atom\packages\linter\lib\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:85:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146396)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147280)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at Package.activateNow (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3296369)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3296147
    at Package.measure (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3293757)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3296007
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3295950)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:382948)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:926785
    at r (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:921391)
    at n (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:1063434)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
     -5:17.5.0 core:confirm (input.hidden-input)
     -5:02.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by aminya** [comment]
Try the latest version
