### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by benogle** [steelbrain/linter#285]
_From @noahcawley on December 10, 2014 16:50_

Uncaught TypeError: Bad argument

**Atom Version**: 0.154.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package
### Steps To Reproduce
1. Open atom with a haskell file (.hs postfix)
2. ...
### Stack Trace

```
At child_process.js:1134

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1134:26)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/opt/atom/resources/app/src/buffered-process.js:40:37)
  at LinterHLint.Linter.lintFile (/home/ncawley/.atom/packages/linter/lib/linter.coffee:142:19)
  at /home/ncawley/.atom/packages/linter/lib/linter-view.coffee:145:18
  at Object.oncomplete (fs.js:93:15)

```

_Copied from original issue: atom/atom#4514_

**Comment by kurtschlatzer** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.3


### Stack Trace

Uncaught TypeError: Bad argument

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at LinterScssLint.Linter.lintFile (/Users/kurtschlatzer/.atom/packages/linter/lib/linter.coffee:178:19)
  at /Users/kurtschlatzer/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/kurtschlatzer/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:45.1.0 core:backspace (input.hidden-input)
  3x -2:40 core:save (input.hidden-input)
  2x -0:32.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-spacegray-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-spacegray-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "autosave",
      "autoflow",
      "background-tips",
      "autocomplete",
      "welcome",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-toml",
      "metrics",
      "open-on-github",
      "pepper-autocomplete",
      "autocomplete-paths",
      "dash",
      "file-templates",
      "git-log",
      "linter-doiuse",
      "package-list",
      "timecop",
      "bookmarks",
      "styleguide",
      "feedback",
      "spell-check",
      "wrap-guide",
      "Remote-FTP",
      "cut-line",
      "lorem-ipsum",
      "w3c-validation",
      "linter-tidy",
      "linter-htmlhint",
      "less-autocompile",
      "language-mustache",
      "linter-less",
      "title-case",
      "pigments",
      "auto-indent",
      "deprecation-cop",
      "esformatter",
      "linter-phpcs",
      "linter-scss-lint",
      "linter-csslint"
    ],
    "projectHome": "/Users/kurtschlatzer/Projects"
  },
  "linter": {
    "lintOnSave": false,
    "statusBar": "Show error of the selected line",
    "showInfoMessages": true,
    "clearOnChange": true,
    "lintDebug": true
  }
}
```

### Installed Packages

```coffee
# User
Package-Upgrader, v0.3.1
atom-beautify, v0.27.1
autoclose-html, v0.16.0
autocomplete-php, v0.3.6
base16-spacegray-syntax, v0.2.0
editorconfig, v1.0.0
indent-guide-improved, v1.2.0
language-generic-config, v0.2.0
language-htaccess, v0.1.1
language-svg, v0.8.0
linter, v0.12.3
linter-jshint, v0.1.4
linter-php, v0.0.12
markdown-preview-opener, v0.1.1
open-last-project, v0.4.1
pretty-json, v0.3.3
synced-sidebar, v0.2.3
text-manipulation, v0.6.0
wordpress-api, v1.2.1

# Dev
No dev packages
```
